Ported Code to support Python3 and made other subtle changes
xychang/RecursiveHierarchicalClustering pull request #9
Opened 2019-11-20 06:36 UTC by Enforcer007

Issue: https://github.com/xychang/RecursiveHierarchicalClustering/issues/6

- Ported Code to Python3
- Made subtle Changes such as args for cPickle reads and writes.

Tested and Checked for recursiveHierarchicalClustering.py

2019-11-20 06:44 UTC, xychang commented on recursiveHierarchicalClustering.py
> +    return True
Love it :D

2019-11-20 06:46 UTC, xychang commented on recursiveHierarchicalClusteringFast.py
> +    def splitCluster(self, xxx_todo_changeme):
maybe change to cluster_info

2019-11-20 06:50 UTC, xychang requested changes
Overall looks good to me. Thank you so much for the effort. Would you mind comparing the results before and after the change, just to make sure everything is the same? Thanks!

2019-11-20 06:50 UTC, xychang commented on recursiveHierarchicalClusteringFast.py
> +        (baseCluster, diameter, cid) = xxx_todo_changeme
ditto

2019-11-20 06:50 UTC, xychang commented on recursiveHierarchicalClusteringFast.py
> +    def splitCluster(self, xxx_todo_changeme):
maybe change to cluster_info

2019-11-20 06:50 UTC, xychang commented on recursiveHierarchicalClusteringFast.py
> +    def evaluateModularityShift(self, xxx_todo_changeme1, sumAB):
just `clusterAB` is fine

2019-11-20 06:50 UTC, xychang commented on recursiveHierarchicalClusteringFast.py
> +        (clusterA, clusterB) = xxx_todo_changeme1
ditto

2019-11-20 08:45 UTC, Enforcer007 commented
K sure, I'll make the changes and will revert after examining the results, shortly.

2019-11-29 07:25 UTC, Enforcer007 commented
Hi @xychang ,

Updated change requests. Also checked the results and are same. Even checked the recursiveHierarchicalClusteringFast.py file. Below are the cluster images.

- Updated recursiveHierarchicalClustering.py (python 3)
![Cluster_updated](https://user-images.githubusercontent.com/6951100/69851206-294d6d80-12a7-11ea-8d2e-dfe4c693b9f5.png)

- Updated recursiveHierarchicalClusteringFast.py (python 3)
![Fast](https://user-images.githubusercontent.com/6951100/69851268-513cd100-12a7-11ea-99cb-1f638c764c66.png)


- Original recursiveHierarchicalClusteringFast.py (python 2)
![Original](https://user-images.githubusercontent.com/6951100/69851236-3ec29780-12a7-11ea-8b71-6ab441b87cac.png)

2019-12-04 06:48 UTC, merged